Feature/license key updates
MadeRightMedia/vista pull request #13
Opened 2023-06-29 22:44 UTC by dav3Herrera

---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - https://app.asana.com/0/0/1204837370215034

2023-07-17 19:43 UTC, dav3Herrera commented on includes/options/license-manager.php
> -      ?><div class="notice notice-success">License key activated successfully</div><?php
I removed this message because it flashes when ever the license key is removed .  Im going to keep it the way it is right now and remove the left over php. I uploaded a video showing the issue. The user already gets to see the enabled and disabled status , if there is an error the license does not activate.

https://github.com/MadeRightMedia/vista/assets/109393522/c4c87b98-94fd-43f1-86e7-d2f8c0229aba

2023-07-17 20:18 UTC, dav3Herrera commented on includes/options/license-manager.php
> +      <img width="125" src="https://vistawp.com/wp-content/uploads/2022/01/cropped-VISTA-Logo-Solo-OK-final_Mesa-de-trabajo-1.png" >
I think they were reffering to external libraries and cdn, not individual assets. if this was the case then we would have to host our own video tutorials on this plugin instead of just sourcing from youtube.

2023-07-17 20:44 UTC, dav3Herrera commented on includes/options/license-manager.php
> +      $page_url = esc_url($_SERVER['REQUEST_URI']);
I tried it withouut the JS but after form submission the status of the page of ACTIVE or DISABLED does not change. the page needs to refresh to view the changes, there may be a different way to do this but its just more complexity. In reality who builds websites without JS anymore ?

2023-07-17 20:59 UTC, dav3Herrera commented on includes/options/license-manager.php
> +    $licenseStatus = $licenseKey ? 'Active' : 'Disabled';
I tried using the $this->is_valid() but it only keeps returning a value of 1 when active or disabled , so essentially it always show active. Its currently working properly and if someone enters an invalid license it just stays disabled.

2023-07-17 21:02 UTC, dav3Herrera commented on includes/options/license-manager.php
> +    $licenseStatus = $licenseKey ? 'Active' : 'Disabled';
also since i added the error message back it shows this when an invalid license is entered 
<img width="1190" alt="Screenshot 2023-07-17 at 3 00 36 PM" src="https://github.com/MadeRightMedia/vista/assets/109393522/ff3dbcc0-5a08-4b96-b28b-bf091271b072">

2023-07-17 21:04 UTC, dav3Herrera commented on includes/options/license-manager.php
> -      ?><div class="notice notice-error">Error: <?php echo esc_html($result) ?></div><?php
I readded this error message

2023-07-19 22:07 UTC, NateLanza commented on includes/options/license-manager.php
> +      <img width="125" src="https://vistawp.com/wp-content/uploads/2022/01/cropped-VISTA-Logo-Solo-OK-final_Mesa-de-trabajo-1.png" >
CDNs often deliver individual assets. Regardless, the problem here is that you're relying on a static link from the vistawp site to deliver an image. If that image ever gets deleted or the permalink changed, this breaks on all sites running vista, and we have to push out an update just for that permalink. Including the image in an `assets` folder with the plugin ensures that it won't break unless we release a broken plugin version.

2023-07-19 22:11 UTC, NateLanza commented on includes/options/license-manager.php
> +      $page_url = esc_url($_SERVER['REQUEST_URI']);
Fair enough! However, since my last comment, I learned that you should be using the `wp_safe_redirect()` function instead of directly echoing JS onto the page.

2023-07-19 22:36 UTC, NateLanza requested changes
Couple minor changes and unresolved conversations- I brought up a couple new things and still need some of the changes from the last review.

2023-07-19 22:36 UTC, NateLanza commented on includes/options/license-manager.php
> +      <p class="vsta-settings-text"> <?php echo esc_html('License Status'); ?> <span class="vsta-<?php echo esc_html(strtolower($licenseStatus)); ?>"> <?php echo esc_html($licenseStatus); ?> </span>
No need to escape the `License Status` string or echo it from php, ha. If it's hardcoded HTML, it won't be vulnerable to injection. Rest of this line looks good 👍

2023-07-21 21:56 UTC, dav3Herrera commented on includes/options/license-manager.php
> +      $page_url = esc_url($_SERVER['REQUEST_URI']);
this function wp_safe_redirect() along with wp_redirect() do no work , they do not refresh the page properly and even though you deactivate the plugin it still shows active, im going to keep it the way it is for now

2023-07-21 23:25 UTC, NateLanza requested changes
Still waiting on changes from the two unresolved conversations

2023-07-21 23:25 UTC, NateLanza commented on includes/options/license-manager.php
> +      $page_url = esc_url($_SERVER['REQUEST_URI']);
Did you place a call to `exit;` directly after the call to `wp_safe_redirect()` as the docs state? You may also try rebasing this onto the latest version of `develop` as it has a bugfix which should ensure that all redirect calls in the plugin work. I think if you do that then this issue will be fixed

2023-07-21 23:50 UTC, dav3Herrera commented on includes/options/license-manager.php
> +      $page_url = esc_url($_SERVER['REQUEST_URI']);
yes i placed exit on both of them

2023-07-26 17:25 UTC, NateLanza commented on includes/options/license-manager.php
> +      $page_url = esc_url($_SERVER['REQUEST_URI']);
Alrighty, I've made an Asana task to fix this later because we just need to get this release out.

2023-07-26 17:31 UTC, NateLanza approved these changes
Two unfinished things are being left for later; appropriate Asana tasks have been created. Overall, this works and is ready to merge; however, I'm leaving it unmerged as it has not been tested and we may want to release without it.

2023-07-26 17:31 UTC, NateLanza commented on includes/options/license-manager.php
> +      <img width="125" src="https://vistawp.com/wp-content/uploads/2022/01/cropped-VISTA-Logo-Solo-OK-final_Mesa-de-trabajo-1.png" >
Ok, I'm resolving this as well and adding an Asana task to fix it later.

2023-07-26 17:46 UTC, merged