Forms fixes
MadeRightMedia/vista pull request #14
Opened 2023-07-12 22:21 UTC by NateLanza

Basic fixes- form redirect error, plus some errors in single-listing that were picked up by my linter.

---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - https://app.asana.com/0/0/1204569300640066

2023-07-12 23:21 UTC, slopeztr requested changes
The line after the `exit;` statement should be removed since, at that point, the program terminates and the last `echo` statement will not be executed.

2023-07-12 23:24 UTC, slopeztr commented
> The line after the `exit;` statement should be removed since, at that point, the program terminates and the last `echo` statement will not be executed.

2023-07-12 23:24 UTC, slopeztr commented
ahh ok, I don't see the another change. @NateLanza

2023-07-14 01:58 UTC, NRLanza commented
Still working on other errors from Marlo's test- https://maderightmedia.slack.com/archives/C0304VCN35L/p1689208627958869

2023-07-21 22:53 UTC, slopeztr commented on includes/api/get-params.php
> +      if ( !empty($_GET[$getName]) ) {
I think this function, being very important, should be optimized at the code level. However, I believe we can leave it as it is for now until we do the refactoring. Regarding the change you made, could you modify the conditional to something like this:

foreach ...
  if ( empty($_GET[$getName]) ) {
     continue:
  }
  
  ... The rest.
  
That way, you eliminate one extra level of conditionals.

2023-07-21 23:03 UTC, slopeztr requested changes

2023-07-21 23:03 UTC, slopeztr commented on vista.php
> +  ob_clean();
If after this line you no longer continue accumulating content in the buffer, use `ob_end_clean()`, which not only clears the buffer but also deactivates output buffering.

2023-07-21 23:03 UTC, slopeztr commented on includes/api/get-params.php
> +      if ( !empty($_GET[$getName]) ) {
I think this function, being very important, should be optimized at the code level. However, I believe we can leave it as it is for now until we do the refactoring. Regarding the change you made, could you modify the conditional to something like this:

```
foreach ...
  if ( empty($_GET[$getName]) ) {
     continue:
  }
```
  
  ... The rest.
  
That way, you eliminate one extra level of conditionals.

2023-07-21 23:36 UTC, NateLanza commented on includes/api/get-params.php
> +      if ( !empty($_GET[$getName]) ) {
This suggestion appears to have the exact same functionality- currently if `$_GET[$getName]` is empty, the entire expression evaluates to false and the loop continues to the next iteration. An optimizing compiler should represent both ways to write it exactly the same way- I'm not sure what the extra level of conditionals you're referring to is.

2023-07-22 01:01 UTC, slopeztr commented on includes/api/get-params.php
> +      if ( !empty($_GET[$getName]) ) {
@NateLanza If it's the same functionality, but what I mean by "level of conditional" is that the code looks more "elegant" when conditionals are not too deeply nested. So, if we can achieve the same outcome by removing one level of nesting within another, it improves the code's readability.

2023-07-22 01:03 UTC, slopeztr commented on includes/api/get-params.php
> +      if ( !empty($_GET[$getName]) ) {
@NateLanza In summary, it's better to have this:

```
if ( empty($_GET[$getName]) ) {
continue;
}

if (what follows...) { ... }
```

Than this:

```
if ( empty($_GET[$getName]) ) {
  if (what follows...) { ... }
}
```

In other words, code is written not only for functionality but also for readability.

2023-07-22 01:08 UTC, slopeztr requested changes

2023-07-22 01:08 UTC, slopeztr commented on includes/forms/Form.php
> +        <form method="GET" id="<?php echo $id; ?>" action="<?php echo \esc_attr($dest) ?>">
Also with the variable `$id`.

2023-07-26 00:27 UTC, dav3Herrera commented on includes/forms/Form.php
> +        <form method="GET" id="<?php echo $id; ?>" action="<?php echo \esc_attr($dest) ?>">
right now these forms are automatically redirecting to a dufferent url, what happens is when you submit the form with GET, the browser auto redirects to the action location without actually processing on the back-end and it automatically creates the url string with the inputs from the form and you get a string that will look like this  (https://vista-dev-site.local/listings/?q=boise&minprice=&maxprice=&minbeds%5B%5D=&minbaths%5B%5D=)

2023-07-26 17:53 UTC, NateLanza commented on includes/forms/Form.php
> +        <form method="GET" id="<?php echo $id; ?>" action="<?php echo \esc_attr($dest) ?>">
Updated this. @dav3Herrera is that an issue? They seem to be working fine

2023-07-26 17:53 UTC, NateLanza commented on includes/api/get-params.php
> +      if ( !empty($_GET[$getName]) ) {
Ah, I understand. This has been updated; resolving this conversation.

2023-07-26 18:03 UTC, dav3Herrera commented on includes/forms/Form.php
> +        <form method="GET" id="<?php echo $id; ?>" action="<?php echo \esc_attr($dest) ?>">
it does this on the vista_basic_form shortcode after form is submitted with just the q form filled out. It could be a browser issue, im working on google chrome. I will test on other browser etc and try to debug this thing ...

2023-07-26 18:48 UTC, NateLanza commented on includes/forms/Form.php
> +        <form method="GET" id="<?php echo $id; ?>" action="<?php echo \esc_attr($dest) ?>">
@dav3Herrera Are you thinking that the `[minbeds%5B%5D=&minbaths%5B%5D=](https://vista-dev-site.local/listings/?q=boise&minprice=&maxprice=&minbeds%5B%5D=&minbaths%5B%5D=)` is an issue? I think you'll get weird stuff depending on the browser if the field is empty, but that shouldn't affect the displayed results since the field names here are invalid. Does it?

2023-07-27 00:29 UTC, dav3Herrera commented on includes/forms/Form.php
> +        <form method="GET" id="<?php echo $id; ?>" action="<?php echo \esc_attr($dest) ?>">
i had this issue with the first version of the forms, it automatically just goes to the action location and adds the weird url string of teh empty fields. but even if it was just adding extra stuff it still has the issue that it does not add  the status=Active to that string, therefore it will not show the active properties and does show a difference in the number of properties. Essentially all your code is being bypassed after submitting the form

2023-07-27 18:04 UTC, NateLanza commented on includes/forms/Form.php
> +        <form method="GET" id="<?php echo $id; ?>" action="<?php echo \esc_attr($dest) ?>">
@dav3Herrera That's a good point about the status; SimplyRETS' docs state that the default status is active, but they indeed return fewer listings when the parameter is explicitly specified. That said, if you're gonna implement a fix for code that someone else is working on, you need to consult first- I removed the code that you re-added in your hotfix for specific reasons, and you shouldn't be making changes that directly undo mine (or @slopeztr's) without discussing it with us first. Anyway, I've fixed the status problem in a way that fits with the current functionality of the code, no redirect required. If you have a pressing reason to go back to the old submit-process-redirect method of form submission, you're welcome to bring it up here or in Slack, but until then I'm sticking with direct submission for speed and reliability. I don't think the errors in the unused URL params are a problem, but if they are, we can solve that easily by adding default values for each form field.

2023-07-27 21:29 UTC, slopeztr approved these changes

2023-07-29 00:49 UTC, merged