Feature/filters shortcode
MadeRightMedia/vista pull request #15
Opened 2023-07-14 19:35 UTC by slopeztr

About task...

[Asana Card](https://app.asana.com/0/1204287686904177/1204569301940715/f)

2023-07-19 21:58 UTC, NateLanza requested changes
See comments- biggest problem is lack of PHPDoc on new functions. Feel free to message me in Slack if you want to discuss any of my corrections; I'm happy to hear more about why you made any particular design decision.

2023-07-19 21:58 UTC, NateLanza commented on includes/api/get-listing-params.php
> +  public static function get_param_list() {
Add a return type and a descriptive PHPDoc comment for this function

2023-07-19 21:58 UTC, NateLanza commented on includes/functions.php
New functions in this file should have types specified for the parameters and return types. If a parameter or return can have more than one type, you can leave the type annotation blank. However, mixed types should be avoided as much as possible, so that type errors fail ASAP at runtime.

Additionally, these functions are missing PHPDoc comments. A simple inline comment is not sufficient; a descriptive comment with details on parameters and return types is necessary.

2023-07-19 21:58 UTC, NateLanza commented on includes/functions.php
> +    return false;
You can return `''` if the license key doesn't exist in order to be able to set the return type to string. This should behave the same way in most situations anyway due to `'' == false`

2023-07-19 21:58 UTC, NateLanza commented on includes/functions.php
> +  function get_call_types( $type ) {
`get_call_type` is a slightly better descriptor

2023-07-19 21:58 UTC, NateLanza commented on includes/functions.php
> +    return false;
Unless you have a good reason not to, I think this function should throw an exception if the call type is not set. The only cause of that problem would be a developer spelling a call type wrong, in which case the error is either thrown here or when they pass `false` to a function expecting a call type. Since their error would have occurred when calling this function, the exception should be thrown here.

2023-07-19 21:58 UTC, NateLanza commented on includes/functions.php
> +  function connect_api_data( $license_key, $call_type, $id = false ) {
Remind me why you wanted a factory function for RETS-API instances? What advantage does this helper have over calling the constructor directly?

2023-07-19 21:58 UTC, NateLanza commented on includes/listings/listing-display-by-filters.php
> +  protected const PARAM_ERR_MSG = "<p>Listing MLS ID must be in the URL parameter 'listing'</p>";
You don't need this error, correct?

2023-07-19 21:58 UTC, NateLanza commented on includes/listings/listing-display-by-filters.php
> +    );
Did you mean to use your helper functions here?

2023-07-19 21:58 UTC, NateLanza commented on includes/listings/single-listing.php
> +        restore_error_handler();
You can remove the `restore_error_handler()` here since we are no longer setting it manually. I'm not sure whether `set_error_handler()` can stack multiple times, but if so, this would error.

2023-07-19 21:58 UTC, NateLanza commented on includes/listings/single-listing.php
> +    $masonry = '<div id="myModal" class="modal">
Haha, this was Dave's error, I also fixed it in one of my branches that has since merged with develop 😄

2023-07-19 21:58 UTC, NateLanza commented on includes/listings/listing-display-by-filters.php
> +   * @var content (optional)
Add more description to this PHPDoc- for example, you can note that it is designed to be called by a shortcode tag. Params and return should be explained as well. If I were a new developer on this project, I might not realize that this is a shortcode function- the current PHPDoc implies that this function filters listing results and nothing else.

2023-07-19 22:00 UTC, NRLanza reviewed
Oop, left my review with my other github account- submitting this to clear the requested review.

2023-07-20 18:42 UTC, slopeztr commented on includes/api/get-listing-params.php
> +  public static function get_param_list() {
@NateLanza @NRLanza You're right, phpdoc was added to the function.

2023-07-20 18:44 UTC, slopeztr commented on includes/functions.php
@NateLanza @NRLanza  That's right, at the time I didn't notice that. I removed the functions that were there because they should be there, only one `str_contains() `call remains. I'm not sure if it can be given a phpdoc comment since I don't have much context of what it does.

2023-07-20 18:44 UTC, slopeztr commented on includes/functions.php
> +    return false;
@NateLanza function removed.

2023-07-20 18:45 UTC, slopeztr commented on includes/functions.php
> +  function get_call_types( $type ) {
@NateLanza function removed.

2023-07-20 18:45 UTC, slopeztr commented on includes/functions.php
> +    return false;
@NateLanza function removed.

2023-07-20 18:45 UTC, slopeztr commented on includes/functions.php
> +  function connect_api_data( $license_key, $call_type, $id = false ) {
@NateLanza function removed.

2023-07-20 18:45 UTC, slopeztr commented on includes/listings/listing-display-by-filters.php
> +  protected const PARAM_ERR_MSG = "<p>Listing MLS ID must be in the URL parameter 'listing'</p>";
That's correct, I have already removed that message.

2023-07-20 18:47 UTC, slopeztr commented on includes/listings/listing-display-by-filters.php
> +    );
@NateLanza The auxiliary functions I want to create are three: to get the license key, to get the call type, and to get the API connection. But it should go in their respective class as we discussed.

2023-07-20 21:10 UTC, NateLanza commented on includes/functions.php
That's fine, I wrote it way back when and didn't document so it'll stay that way for now

2023-07-20 21:12 UTC, NateLanza commented on includes/listings/single-listing.php
> +        restore_error_handler();
Leaving this up for the minute, but I believe it will be fixed with the rebase

2023-07-21 22:10 UTC, slopeztr commented on includes/listings/single-listing.php
> +    $masonry = '<div id="myModal" class="modal">
@NateLanza I saw the development branch, and your change wasn't there. I sent it again through my branch in case it generates a conflict for you.

2023-07-21 22:23 UTC, slopeztr commented on includes/listings/listing-display-by-filters.php
> +   * @var content (optional)
@NateLanza Done.

2023-07-21 22:24 UTC, slopeztr commented
@NateLanza I made the final changes and rebased with the develop branch; I don't think it should give you any problems.

2023-07-21 22:56 UTC, NateLanza approved these changes
Looks good

2023-07-21 22:56 UTC, merged